### ISSUE TITLE
janitor fails to install if protobuf-compiler is not installed

### ISSUE THREAD

**Issue by venthur** [jelmer/janitor#294]
janitor fails to install via `pip install .[dev]` if protobuf-compiler is not installed on the host system. this id probably due to the requirement of `setuptools_protobuf` in `pyproject.toml` and this line here:

https://github.com/jelmer/setuptools-protobuf/blob/main/setuptools_protobuf/__init__.py#L22

which just fails if it can't find the thing it needs. so setting up the environment fails.

**Comment by jelmer** [comment]
That's correct, you need to install the external dependencies listed in CONTRIBUTING.md before running pip install. There's no way around that AFAICT.

**Comment by jelmer** [comment]
Closing since I think there's nothing we can do about this - please reopen if I've missed something.
