### ISSUE TITLE
Cannot get all tests run locally

### ISSUE THREAD

**Issue by venthur** [jelmer/janitor#72]
Hi,

I'd like to contribute a bit to this repo. Step 1 is usually to get the tests running, so I can make sure things work as expected before and after the changes. However, I'm already struggeling with step 1 :) Here's what I'm doing:

```
# create a venv
python3 -m venv venv
. venv/bin/activate
pip install -U pip setuptools
pip install -e .[dev]

make test
```

some tests run, but three do not because of this error:

```

======================================================================
ERROR: test_worker (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_worker
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/venthur/git/janitor/janitor/tests/test_worker.py", line 18, in <module>
    from janitor.worker import bundle_results
  File "/home/venthur/git/janitor/janitor/worker.py", line 56, in <module>
    from silver_platter.workspace import Workspace
  File "/home/venthur/git/janitor/venv/lib/python3.10/site-packages/silver_platter/__init__.py", line 26, in <module>
    import breezy.plugins.debian  # For apt: URL support  # noqa: F401
ModuleNotFoundError: No module named 'breezy.plugins.debian'
```

I see you do some magic in the makefile to install the plugin (allthough i'm not sure what breezy or the plugin does) but how can i reproduce this environment on my machine?

**Comment by jelmer** [comment]
The repository has evolved quite a bit over time, which is why it has ended up with a set of submodules rather than with things in pip.

I've now put up a PR that moves the repo to a somewhat more traditional model. https://github.com/jelmer/janitor/pull/104

**Comment by venthur** [comment]
I haven't tested this branch yet, but until you mentioned it, i completely overlooked the git submodues. :D now the tests in the old branch work.

looking at the diff of your draft, i like it a lot better! maybe you've forgotten to update the makefile where you run some tests in the submodules in the `test-it-all` target?

**Comment by jelmer** [comment]
FWIW this has now all landed, so please give it another go. CONTRIBUTING.md has basic instructions.
