### ISSUE TITLE
test_suite in setup.py is deprecated

### ISSUE THREAD

**Issue by venthur** [jelmer/janitor#73]
would you mind if i modernize this setup a bit? I'd like to utilize [pytest](https://docs.pytest.org/en/7.1.x/) which is pretty standard nowadays. The code for the tests can be then simplified a lot, you don't need the testcases classes anymore but can write simple `test_` functions instead and use `assert` instead of `unitest`'s crufty `self.assertX` methods.

**Comment by jelmer** [comment]
Sure, that sounds good.
